### ISSUE TITLE
adicionar função "extrai_NomeProprio()"

### ISSUE THREAD

**Issue by lucasmation** [ipea/validaRA#8]
extrai_NomeProprio()

- recebe uma string contendo nome, possivelmente completo.
- Compara esta string com uma lista preexistente de nomes próprios, inclundo nomes compostos
- retorna apenas o nome próprio
- talvez função pudesse contem o parametro sexo, por defaul seria vaizo (sexo=NULL), mas se a pessoa preencher, ele restringiria a busca de nomes próprios por sexo. 

@igornoberto  favor produzir esta lista e começar a criar a função. 
@gutorc92 , @daniellima123 : favor ajudem o Igor com a função (bem documentada, etc).

**Comment by lucasmation** [comment]
@igornoberto : acho que não precisamos de um pacote novo, basta criar a função aqui no validaRA (para o metaphone vamos precisar). Como está indo isso?

**Comment by igornoberto** [comment]
@lucasmation As funções de separar nomes proprios e identificar o sexo estão prontas. Estava terminando de ler o material de criação de pacotes para inserir essas funções no package.

**Comment by igornoberto** [comment]
@lucasmation não possuo permissão para o mesmo.

$ git push
remote: Permission to ipea/validaRA.git denied to igornoberto.
fatal: unable to access 'https://github.com/ipea/validaRA.git/': The requested URL returned error: 403

**Comment by lucasmation** [comment]
tenta de novo, te mandei um convite para fazer parte do projeto e poder dar
push

2017-04-12 14:33 GMT-03:00 igornoberto <notifications@github.com>:

**Comment by igornoberto** [comment]
@lucasmation 

Done!
